{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-grafana
  namespace: {{ include "observability.namespace" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: web
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
{{- end }}


