apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geth-node.fullname" . }}
  labels:
    {{- include "geth-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geth-node.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geth-node.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: geth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range .Values.geth.args }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: p2p
              containerPort: 30303
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: /root/.ethereum
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-data" (include "geth-node.fullname" .)) .Values.persistence.existingClaim }}


